name: 'Sync Echo State'
description: 'Sync state from your Echo deployment to Novu cloud'
author: 'Novu'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  novu-api-key:
    description: 'Your Novu API key'
    required: true
  echo-url:
    description: 'Your Echo deployment endpoint URL'
    required: true
  backend-url:
    description: 'Your Echo deployment endpoint URL'
    required: false
    default: 'https://api.novu.co'

# Define your outputs here.
outputs:
  success:
    description: 'The status of the sync'
  result:
    description: 'The sync result object'
runs:
  using: node20
  main: dist/index.js
